### PR TITLE
Resolve issue #63

### LINKED ISSUE #63: CommitButNoPush variable gets reset to 0 when reloading app
## Problem
When I commit and then reload the application I can no longer push.

## steps to reproduce
1. Commit changes
2. reload the app
3. try and push

## suggested fix
- ensure CommitButNoPush variable is set appropriately when restarting the app.

### PR DESCRIPTION
**Pull request by smithmr**
## Solves
- issue #63 This issue had to be expanded to resolve the push functionality.

## how it works
- There are 4 cases when pushing
- Local branch is up to date with origin
- Local branch is ahead of origin
- Local branch is behind origin
- origin does not exist

## Implementation
- Created function `checkIfExistOrigin(branchName)` takes in the name of the current branch and checks if the origin version of the branch exist
- Created function `getAheadBehindCommits(branchName)` takes in the name of the current branch and return the number of commits your local branch is ahead of and behind of origin.
- Updated function `pushToRemote()` to call `checkIfExistOrigin(branchName)` and notifies the user if the origin version of their branch does not exist.
- Updated function `pushToRemote()` to call `getAheadBehindCommits(branchName)` and notify the user if the local branch is up to date with origin, behind origin, or to push if the local branch is ahead of origin.

closes #63

### CODE REVIEW

**Comment by mdesco18** [comment]
I am not able to do a push at all. I think the program gets stuck inside function getAheadBehindCommits. Consider added console.log statements to debug.

**Comment by smithmr** [comment]
> I am not able to do a push at all. I think the program gets stuck inside function getAheadBehindCommits. Consider added console.log statements to debug.

Updated the description of the PR, it will only work if you are on Master right now.

**Review by mdesco18 — APPROVED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
Tested 2/4 cases locally on Windows 10. Saw the other 2 cases test via screen share on Mac. Cases passed and function work flow is correct in solving the issue. 
**Is the code well documented? Would it be easily understood to other developers?**
code is documented for added functions and the documentation provided explains the issue fix well
**Does it have correct linting/formatting?**
yes the formatting follows the codebase
**Is there any redundant or duplicate code? Any hard-coded values?**
no
**Can any of the code be replaced with library functions?**
no, it uses nodegit API
**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
yes
**Were any other issues found?**
No, some error messages could be considered a catch all for uninitialized repositories but the explanations are sufficient

good job matt

**Comment by Leon0315** [comment]
> > I am not able to do a push at all. I think the program gets stuck inside function getAheadBehindCommits. Consider added console.log statements to debug.
> 
> Updated the description of the PR, it will only work if you are on Master right now.
it's not merged into master yet, how Can I test it on master? I am not able to push on a testing branch pulled from issue-63 @smithmr

**Comment by aujlarj** [comment]
When I tried to commit -> push in VisualGit I got this:
image

but when I did git push on terminal/cmd I got this:
image

Shouldn't the VisualGit allow to push? since the command `git push` from terminal worked and currently I don't have to create an upstream to push. 

@smithmr

**Comment by cchampernowne** [comment]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.
- I got all four cases to work at least once. Could only get "Local branch is up to date with origin" and 
"Local branch is ahead of origin" respectfully.
Is the code well documented? Would it be easily understood to other developers?
-yes. good comments explain the logic flow
code is documented for added functions and the documentation provided explains the issue fix well
Does it have correct linting/formatting?
-yes
Is there any redundant or duplicate code? Any hard-coded values?
-no
Can any of the code be replaced with library functions?
-no
Are good names used for methods, variables, etc.? Do they follow naming conventions?
-yes
Were any other issues found?
some errors present from master impeded testing (spinning wheel of death)

**Review by cchampernowne — APPROVED** [review]
Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.

I got all four cases to work at least once. Could only get "Local branch is up to date with origin" and
"Local branch is ahead of origin" respectfully.
Is the code well documented? Would it be easily understood to other developers?
-yes. good comments explain the logic flow
code is documented for added functions and the documentation provided explains the issue fix well
Does it have correct linting/formatting?
-yes
Is there any redundant or duplicate code? Any hard-coded values?
-no
Can any of the code be replaced with library functions?
-no
Are good names used for methods, variables, etc.? Do they follow naming conventions?
-yes
Were any other issues found?
-some errors present from master impeded testing (spinning wheel of death)

File: app/misc/git.ts [hunk 1]
```diff
@@ -747,43 +749,96 @@ function pullFromRemote() {
...
+        if (!remoteBranchExist) {
+            window.alert("fatal: The current branch test-branch has no upstream branch.\n" +
+                "To push the current branch and set the remote as upstream, use\n" +
+                "\n" +
+                "    git push --set-upstream origin test-branch");
+            return;
+        } else {
+            // tells the user if their branch is up to date or behind the remote branch
+            getAheadBehindCommits(branch).then(function (aheadBehind) {
+                if (aheadBehind.ahead === 0) {
```
Comment (ajlarivi) [inline app/misc/git.ts]: should this if and its else statement not be switched? In the case that you are not ahead any commits locally but are still behind the remote (ie. aheadBehind.ahead = 0 and aheadBehind.behind > 0) you would want to receive the "your branch is behind remote by..." instead of "your branch is up to date"

**Review by ajlarivi — CHANGES_REQUESTED** [review]
**Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**

Running linux mint I was able to test and confirm local functionality of:
- _Local branch is up to date with origin_
- _Local branch is ahead of origin_
- _origin does not exist_: as for the issue @aujlarj metnioned when attempting this test case in the terminal I get the following. 
git push 
so visual git is mirroring what happens in the terminal as we would like, maybe a difference in how RJ's git is configured. 


I was unable to test and confirm the following
- _Local branch is behind origin:_ It seems to be an issue with the getAheadBehindCommits function. below you can see my remote is ahead thus pushing through the command line throws an error. Despite this, the log statement I added to the push function of visual git reports aheadBehind.behind = 0 and visual git continues through to attempt the push, hanging indefinitely. 
issuesbox

**Is the code well documented? Would it be easily understood to other developers?**
code is well documented, comments at the beginning of each function, strong naming convention. 

**Does it have correct linting/formatting?**
linting and formatting good, code is clear and readable. 

**Is there any redundant or duplicate code? Any hard-coded values?**
none found.

**Can any of the code be replaced with library functions?**
None found

**Are good names used for methods, variables, etc.? Do they follow naming conventions?**
function names are clear, proper convention followed.

Were any other issues found?
- if statement ordering, see [comment](https://github.com/uvicgse/project-virtual-team-2/pull/70/files#r291797804)

**Review by ajlarivi — APPROVED** [review]
> **Does the code work? Did I test it locally? What OS am I using? Does it perform its intended function, the logic is correct etc.**
> 
> Running linux mint I was able to test and confirm local functionality of:
> 
> * _Local branch is up to date with origin_
> * _Local branch is ahead of origin_
> * _origin does not exist_: as for the issue @aujlarj metnioned when attempting this test case in the terminal I get the following.
>   git push
>   so visual git is mirroring what happens in the terminal as we would like, maybe a difference in how RJ's git is configured.
> 
> I was unable to test and confirm the following
> 
> * _Local branch is behind origin:_ It seems to be an issue with the getAheadBehindCommits function. below you can see my remote is ahead thus pushing through the command line throws an error. Despite this, the log statement I added to the push function of visual git reports aheadBehind.behind = 0 and visual git continues through to attempt the push, hanging indefinitely.
>   issuesbox
> 
> **Is the code well documented? Would it be easily understood to other developers?**
> code is well documented, comments at the beginning of each function, strong naming convention.
> 
> **Does it have correct linting/formatting?**
> linting and formatting good, code is clear and readable.
> 
> **Is there any redundant or duplicate code? Any hard-coded values?**
> none found.
> 
> **Can any of the code be replaced with library functions?**
> None found
> 
> **Are good names used for methods, variables, etc.? Do they follow naming conventions?**
> function names are clear, proper convention followed.
> 
> Were any other issues found?
> 
> * if statement ordering, see [comment](https://github.com/uvicgse/project-virtual-team-2/pull/70/files#r291797804)

- if statement issue resolved in recent [commit](https://github.com/uvicgse/project-virtual-team-2/pull/70/commits/ff5035cf5720dbc26d242f82c5cc08e20cbd78fb)
-  my struggle to recreate the _Local branch is behind origin_ case was just a case of me not performing a fetch to the remote.

Approving merge
